name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v2'
      with:
      workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
      service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/cloudrun/hello'

    # - name: Deploy to Cloud Run
    #   run: |
    #     gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-simple-php-app
    #     gcloud run deploy my-simple-php-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-simple-php-app --platform managed --region ${{ secrets.GCP_REGION }} --allow-unauthenticated

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'