name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ github.repository }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # - id: 'deploy'
    #   uses: 'google-github-actions/deploy-cloudrun@v2'
    #   with:
    #     service: 'hello-cloud-run'
    #     image: 'gcr.io/cloudrun/hello'

    # - name: Deploy to Cloud Run
    #   run: |
    #     gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}
    #     gcloud run deploy ${{ env.SERVICE_NAME }} --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }} --platform managed --region ${{ secrets.GCP_REGION }} --allow-unauthenticated

    # - name: 'Use output'
    #   run: 'curl "${{ steps.deploy.outputs.url }}"'


    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}
    
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: '${{ env.SERVICE_NAME }}'
        image: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}'
        region: ${{ secrets.GCP_REGION }}
        allow-unauthenticated: true

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'



